### ISSUE TITLE
Upgrade to tokio 0.3

### ISSUE THREAD

**Issue by enterprisey** [magnusmanske/mediawiki_rust#38]
Ah, ecosystem churn.

**Comment by magnusmanske** [comment]
Won't work at the moment because of reqwest (and that because of hyper). Wait for upstream I guess...

**Comment by legoktm** [comment]
This was done on the tokio-1.0 branch and released as 0.2.6, I guess it just needs to be merged into master now? I've been using it for a while with no issues.
