### ISSUE TITLE
Offer async API

### ISSUE THREAD

**Issue by vbrandl** [magnusmanske/mediawiki_rust#5]
Hi,
have you thought about providing an async API? Since you are using reqwest, it should be easily possible by using `reqwest::async::Client` and returning futures instead of results.

**Comment by magnusmanske** [comment]
I started https://github.com/magnusmanske/mediawiki_rust/tree/async but I'm not really happy with the approach, maybe because async is still a bit unstable, maybe because I haven't really worked with it yet. Comments and PRs welcome!

**Comment by magnusmanske** [comment]
Default `Api` struct is now async (use `ApiSync` for the old one)
